### ISSUE TITLE
Dealing with non UTF8 data

### ISSUE THREAD

**Issue by ghola** [zumba/json-serializer#23]
I believe the serializer should be able to handle non UTF8 data. Using a serializer in a messaging system should not limit the type of data you throw at it: what goes in on one side should come out exactly like that on the other side.

I am currently implementing this feature making heavy use of the mbstring extension (for detecting the string encoding and doing conversions). The idea is that whenever I encounter a string that is not UTF8 encoded, I assume it as being with 8bit encoding, convert it to UTF8 on serialization and then convert it back from UTF8 to 8bit during deserialization. This way, if junk comes in, junk comes out without any modifications.

In principle, would you accept such a pull request, or do you have a different vision regarding the capabilities of this library? I'm asking because if you are not interested in this feature I will prefer to internalize this library (a refactored version of it) into my project instead of building it onto the existing code.

**Comment by jrbasso** [comment]
That totally makes sense and is desired on this library. This is actually listed as a limitation on the readme:

> Binary String or malformed UTF8 strings (ie, resulsts from SELECT AES_ENCRYPT(:content, :key) as encrypted)
> These strings will need to be properly handled by converting to hex using bin2hex or utf8_encode in the __sleep() method

We tried to fix it via #4, it solved few cases, but not all. The solution at that point was basically to use the `JSON_UNESCAPED_UNICODE` option from `json_encode`. A better solution covering all cases would be ideal.

The only thing we would like to keep is to have a version that would be readable by languages other than PHP.

Thanks for your contributions.

**Comment by jrbasso** [comment]
Resolved on #24
