### ISSUE TITLE
Allow JSON_PRETTY_PRINT

### ISSUE THREAD

**Issue by williamdes** [zumba/json-serializer#46]
https://github.com/zumba/json-serializer/blob/1288ee15e04b88a152672bf683cd84726ed38e4c/src/JsonSerializer/JsonSerializer.php#L118

**Comment by williamdes** [comment]
At phpMyAdmin while adding your lib on our tests I had to hack this to enable pretty print because reading diffs on PRs is very important for us.

```php
        $serializer = new JsonSerializer();
        $encoded = $serializer->serialize($test);
        $encoded = json_encode(json_decode($encoded), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_PRESERVE_ZERO_FRACTION);
```

**Comment by williamdes** [comment]
See: https://github.com/phpmyadmin/sql-parser/commit/9f16b246ba0752b0cbf568e469cb2559cb3ace4a#diff-0d94b49ce07c850be01bd53aec4c0f967f08954cc7d542d6d5ee35d7015c2a82R162

**Comment by williamdes** [comment]
Hi @jrbasso 
Should I make a PR ?

**Comment by jrbasso** [comment]
@williamdes Sorry, I totally missed this issue. I'm sorry.

I think just adding the `JSON_PRETTY_PRINT` on that list would cause backward incompatibility and a possibility of break some systems that expect always one line. Also, it goes inverse as optimization.
However, I think the case is valid and maybe adding a new method to specify the encoding modifiers is a good way to handle it, so it becomes optional and whoever set these flags will expect a different output format.

**Comment by williamdes** [comment]
> I think just adding the JSON_PRETTY_PRINT on that list would cause backward incompatibility and a possibility of break some systems that expect always one line. Also, it goes inverse as optimization.
However, I think the case is valid and maybe adding a new method to specify the encoding modifiers is a good way to handle it, so it becomes optional and whoever set these flags will expect a different output format.

Sure !
We will be happy to use this new function as for us the diff between JSON files needs to be visible

Here is the old diffs, totally un-readable PHP serialize data: https://github.com/phpmyadmin/sql-parser/commit/b60d7e70415aa62493296068a072923e251be5ce

And here you can see that with you lib and pretty json it make quite a difference in changes tracking !
See: https://github.com/phpmyadmin/sql-parser/commit/e0ba76f6145d7282a1a9ab5dd3ae66ce9ac9e8df#diff-5223b8b0039f0b42219f7e98df65f2f0b2595a3a3880a5376502a25d1679be73
