### ISSUE TITLE
PHP 8.4 : Deprecated implicit nullable

### ISSUE THREAD

**Issue by marcimat** [zumba/json-serializer#61]
Hello,

PHP 8.4 shows at least one deprecated : 
```
Deprecated: Zumba\JsonSerializer\JsonSerializer::__construct(): Implicitly marking parameter $closureSerializer as nullable is deprecated, the explicit nullable type must be used instead in ~/src/JsonSerializer/JsonSerializer.php on line 78
```

This is a small correction

```diff
    public function __construct(
-       ClosureSerializerInterface $closureSerializer = null,
+      ?ClosureSerializerInterface $closureSerializer = null,
        $customObjectSerializerMap = []
    ) {
```

But it seems to be a problem as this syntax comes with PHP 7.1 https://www.php.net/manual/en/migration71.new-features.php 
and this lib accepts PHP >= 7.0 at this time.

**Comment by williamdes** [comment]
This will hit me soon in Debian: https://salsa.debian.org/phpmyadmin-team/sql-parser/-/jobs/6734113#L590

@jrbasso should we drop old PHP versions ?

**Comment by jrbasso** [comment]
I think it's time to drop PHP 7 support. It is still being used by 15% of the installs (https://packagist.org/packages/zumba/json-serializer/php-stats#3), but PHP 7 EOL is over 2 years.

Do you want to create a PR? I can create a new major version after the merge.

**Comment by williamdes** [comment]
Awesome, thank you for the fast reply !

Here you go: https://github.com/zumba/json-serializer/pull/62

**Comment by jrbasso** [comment]
It's now live on the version 3.2.2.

Thank you!
